

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 8.9
  
script:
# Client
  - cd client
  - npm install
  - npm run build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run lint
  - npm run test
  - npm run e2e
  - ng build
# Server
  - cd ../server
  - npm install
  - npm build
